// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
  "swagger": "2.0",
  "info": {
    "title": "Create Shippment API",
    "description": "API for creating shipments.",
    "contact": {}
  },
  "paths": {
    "/api/shippment/create": {
      "post": {
        "summary": "Create a new shipment",
        "description": "This endpoint allows you to create new shipments.",
        "tags": ["shippment"],
        "consumes": ["application/json"],
        "produces": ["application/json"],
        "parameters": [
          {
            "in": "body",
            "name": "shipment",
            "description": "Data for creating a shipment",
            "required": true,
            "schema": {
              "type": "object",
              "properties": {
                "orderID": {
                  "type": "integer",
                  "description": "ID of the order"
                },
                "carrierID": {
                  "type": "integer",
                  "description": "ID of the carrier"
                }
              },
              "required": ["orderID", "carrierID", "status"]
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Shipment created successfully",
            "schema": {
              "type": "object",
              "properties": {
                "message": {
                  "type": "string",
                  "example": "Shipment created successfully"
                },
                "shipment-assignment": {
                  "$ref": "#/definitions/Shipment"
                }
              }
            }
          },
          "400": {
            "description": "Error creating shipment",
            "schema": {
              "type": "object",
              "properties": {
                "error": {
                  "type": "string"
                }
              }
            }
          },
          "500": {
            "description": "Server Error",
            "schema": {
              "type": "object",
              "properties": {
                "error": {
                  "type": "string"
                }
              }
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Shipment": {
      "type": "object",
      "properties": {
        "shipmentID": {
          "type": "string",
          "description": "ID of the shipment"
        },
        "orderID": {
          "type": "integer",
          "description": "ID of the order"
        },
        "carrierID": {
          "type": "integer",
          "description": "ID of the carrier"
        },
        "state": {
          "type": "string",
          "description": "Status of the shipment",
          "default": "Asigned"
        },
        "dateAsignment": {
          "type": "string",
          "format": "date-time",
          "description": "Date when the shipment was assigned"
        }
      },
      "required": ["orderID", "carrierID"]
    }
  }
}`


var SwaggerInfo = &swag.Spec{
	Version:     "1.0",
	Host:        "localhost:8080",  
	BasePath:    "/",
	Schemes:     []string{"http"},
	Title:       "Create Shippment API",
	Description: "API for managment shipments.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
