swagger: "2.0"
info:
  title: "Create Shippment API"
  description: "API for managnment Shippemnt"
  contact: {}
paths:
  "/api/shippment/create":
    post:
      summary: "Create a new Shippment"
      description: "This endpoint allow create a new shippment to database"
      tags:
        - "shippment"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "shipment"
          description: "Data of Shippment"
          required: true
          schema:
            $ref: "#/definitions/Shipment"
      responses:
        "201":
          description: "Shippment created succesfully"
          schema:
            type: "object"
            properties:
              message:
                type: "string"
              shippment-asignment:
                $ref: "#/definitions/Shipment"
        "400":
          description: "Error to create shippment"
          schema:
            type: "object"
            properties:
              error:
                type: "string"
        "500":
          description: "Server Error"
          schema:
            type: "object"
            properties:
              error:
                type: "string"
definitions:
  Shipment:
    type: "object"
    properties:
      shipmentID:
        type: "integer"
        description: "ID_Shippment (auto-generated)"
      orderID:
        type: "integer"
        description: "ID_Orden"
      carrierID:
        type: "integer"
        description: "ID_User_Carrier"
      state:
        type: "string"
        description: "Status of the shipment"
        default: "pendiente"
      dateAsignment:
        type: "string"
        format: "date-time"
        description: "Date when the shipment was assigned"
    required:
      - "orderID"
      - "carrierID"
